spring:
  application:
    name: nacos-client
  cloud:
    nacos:
      password: nacos
      username: nacos
      discovery:
        instance-enabled: true
        weight: 1
      server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:nacos-client.yaml