spring:
  application:
    name: nacos-client
  cloud:
    nacos:
      password: 123321
      username: nacos
      config:
        file-extension: yaml
        extension-configs:
          - data-id: config-example-1
            refresh: true
      discovery:
        instance-enabled: true
        weight: 1