nacos:
    passwd: 123321
    server-addr: 127.0.0.1:8848
    user-name: nacos
server:
    shutdown: graceful
spring:
    application:
        name: nacos-client-auth-test
logging:
    level:
        #    root: error
        root: info